<div class="span-18 last">
    
    <div class="span-6 first box">
        <a href="<?= $this->url(array('controller' => 'admin' , 'action' => 'add-newsletter')) ?>">
        Nytt nyhetsbrev
        </a>
    </div>
    <div class="span-6 box">
        <a href="<?= $this->url(array('controller' => 'admin' , 'action' => 'newsletter-list')) ?>">
            Lista över nyhetsbrev</a></div>
    
    <div>Send newsletters manual</div>
    
    
</div>